export const Products = [
  {
    id: 1,
    title: 'Brown Eggs',
    quantity: '4pcs',
    image: require('./assets/1.jpg'),
    price: 1.99,
  },
  {
    id: 2,
    title: 'Sweet Fresh Stawberry',
    quantity: '200gm',
    image: require('./assets/2.jpg'),
    price: 12.99,
  },
  {
    id: 3,
    title: 'Asparagus',
    quantity: '50gm',
    image: require('./assets/3.jpg'),
    price: 10.0,
  },
  {
    id: 3,
    title: 'Green Smoothie',
    quantity: '30ml',
    image: require('./assets/4.jpg'),
    price: 13.0,
  },
  {
    id: 5,
    title: 'Raw Legums',
    quantity: '50gm',
    image: require('./assets/5.jpg'),
    price: 25.0,
  },
  {
    id: 6,
    title: 'Baking Cake',
    quantity: '100gm',
    image: require('./assets/6.jpg'),
    price: 20.0,
  },
  {
    id: 7,
    title: 'Pesto with Basil',
    quantity: '50gm',
    image: require('./assets/7.jpg'),
    price: 18.19,
  },
  {
    id: 8,
    title: 'Hazelnut',
    quantity: '2gm',
    image: require('./assets/8.jpg'),
    price: 27.35,
  },
  {
    id: 9,
    title: 'Fresh Stawberry',
    quantity: '100gm',
    image: require('./assets/9.jpg'),
    price: 30.0,
  },
  {
    id: 10,
    title: 'Lemon',
    quantity: '40gm',
    image: require('./assets/10.jpg'),
    price: 15.79,
  },
  {
    id: 11,
    title: 'Homemade Bread',
    quantity: '4pcs',
    image: require('./assets/11.jpg'),
    price: 16.0,
  },

  {
    id: 12,
    title: 'Fresh Tomato',
    quantity: '75gm',
    image: require('./assets/12.jpg'),
    price: 23.0,
  },
  {
    id: 13,
    title: 'Green Beans',
    quantity: '30gm',
    image: require('./assets/13.jpg'),
    price: 28,
  },

  {
    id: 14,
    title: 'Strawberry Jelly',
    quantity: '35gm',
    image: require('./assets/14.jpg'),
    price: 14.18,
  },
  {
    id: 15,
    title: 'Pears Juice',
    quantity: '500ml',
    image: require('./assets/15.jpg'),
    price: 19.99,
  },
];
